# Generated by Django 5.2 on 2025-07-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_progresslog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresslog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='progresslog',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='subject',
            field=models.CharField(default='Chưa đặt tên', max_length=100),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa hoàn thành'), ('done', 'Hoàn thành')], max_length=20),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='task_title',
            field=models.TextField(),
        ),
    ]
