# Generated by Django 5.2 on 2025-07-17 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_progresslog_updated_at_progresslog_day_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa hoàn thành'), ('done', 'Đã hoàn thành')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='subject',
            field=models.CharField(default='Tin học', max_length=100),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='week',
            field=models.PositiveIntegerField(),
        ),
    ]
